crowdsourcingGame/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/logout/
    path('logout_view/', views.logout_view, name='logout_view'),
    #path('q2/', views.q2, name='q2'),
    #path('q3/', views.q3, name='q3'),
    path('login_view/', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
]

polls/models.py
import datetime

from django.db import models
from django.conf import settings
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=300)

    def __str__(self):
        return self.question_text

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    answer_order = models.IntegerField(default=0)
    votes = models.IntegerField(default=0)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.answer_text

# class isRelatedTo(models.Model):
#     question1 = models.ForeignKey(Question, related_name="question1", primary_key=True, on_delete=models.CASCADE)
#     question2 = models.ForeignKey(Question, related_name="question2", on_delete=models.CASCADE)
#     question3 = models.ForeignKey(Question, related_name="question3", on_delete=models.CASCADE)

#     def __str__(self):
#         return "<IsRelatedTo: {} {}>".format(self.question2, self.question3)

#     def getRelatedQuestion2(self):
#         return self.question2

#     def getRelatedQuestion3(self):
#         return self.question3

polls/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'style':"margin-top:35px; height:35px; width:30%; font-size:20px;"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'style':"height:35px; width:30%; font-size:20px;"}))
    class Meta():
        model = User
        fields = ('username','password')

polls/views.py
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question,Answer #isRelatedTo
from django.shortcuts import render,get_object_or_404, redirect
from django.urls import reverse
import operator
from nltk.corpus import stopwords 
from django.conf import settings
import random
from random import choice
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm
from collections import OrderedDict
from statistics import mean
from django.db import connection


def index(request):

    submitbutton = request.POST.get('submit')
    nextQuestion = request.POST.get('nextQuestion')
    answer = request.POST.get('answer')
    model = settings.WORD2VEC

    print("username:", request.user.username)
    cursor = connection.cursor()
    cursor.execute('select count(*) as total from auth_user;')
    numOfUsers= Answer.objects.raw("select count(*) as total from auth_user;")
    row = cursor.fetchone()
    numOfUsers = row[0]

    #not logged in
    if not request.user.is_authenticated:
        return render(request, 'polls/login.html', {})
    
    #first time logged in
    if  request.session.get('question_id') is None:
        print ('First time logged in')
        q= Question.objects.raw("select * from polls_question where id not in (select question_id from polls_answer,auth_user where user_id=auth_user.id and auth_user.username='"+request.user.username+"');")
        list=[]
        for p in q:
            list.append(p.id)

        if list == []:
            messages.error(request,'You have already replied all the questions!')
            return logout_view(request)
        
        rnd = random.choice(list)
        print (rnd)
        print (list)
        latest_question = Question.objects.get(pk=rnd)
        request.session['question_id']=rnd
        list.remove(rnd)
        request.session['remaining_questions']=list
        print (list)
    elif nextQuestion is not None:
        print("Clicked next question")
        list = request.session['remaining_questions']
        if list == []:   
            request.session.flush()
            logout(request)
            return logout_view(request)
        rnd = choice([i for i in list if i not in [request.session['question_id']]])
        print (rnd)
        list.remove(rnd)
        latest_question = Question.objects.get(pk=rnd)
        request.session['question_id']=rnd
        request.session['remaining_questions']=list
    else:
        latest_question = Question.objects.get(pk=request.session['question_id'])

    if request.session.get("score") is None:
        request.session["score"]=0

    if request.session.get("list_of_answers") is None:
        request.session["list_of_answers"]=OrderedDict()
    
    scores={}
    list_of_answers=OrderedDict()
    print(answer)
    if answer is not None:
        if len(request.session['list_of_answers']) == 14:
            messages.info(request, 'No more answers needed! Click the next question button to continue...')
            context = {
                'latest_question': latest_question,
                'answer': answer,
                'closest_item': None,
                'score': request.session['score'],
                'list_of_answers': request.session['list_of_answers'] }
            return render(request, 'polls/index.html', context)

        scores = check_similarity(answer, model, latest_question)
        sortedItems = sorted(scores.items(), key=operator.itemgetter(1))
        print(sortedItems)
        closest_item = sortedItems[len(sortedItems)-1][0]

        if len(sortedItems)==0:
            closest_item = None
            score = 0
        else:
            filteredItems= []
            for item in sortedItems:
                if item[1]>=0.8:
                    filteredItems.append(item)
            print(filteredItems)
            
            if (len(filteredItems)==0):
                score=0
            else:
                flat_list = [sublist[1] for sublist in filteredItems]
                meanScore = sum(flat_list) / len(flat_list)
                score = int(round((len(filteredItems)/numOfUsers)*100*meanScore))
                print(len(filteredItems)/numOfUsers)
                print((len(filteredItems)/numOfUsers)*100*meanScore)
                print(score)

        if request.session['list_of_answers'] is None:
            list_of_answers[answer]=score
        else:
            list_of_answers=request.session['list_of_answers']
            list_of_answers[answer]=score     
        request.session['list_of_answers'] = list_of_answers
        score = request.session['score'] + score
        request.session['score'] = score

        print(request.user)        
        saved_answer = Answer(question = latest_question, user = request.user, answer_text = answer, answer_order = len(request.session['list_of_answers']), votes = 0, score = score)
        saved_answer.save()
    elif nextQuestion is not None:
        closest_item=None
        score=request.session['score']
        list_of_answers=OrderedDict()
        request.session['list_of_answers']=OrderedDict()
    else:
        closest_item=None
        score=request.session['score']
        list_of_answers=request.session['list_of_answers']
    
    context = {
        'latest_question': latest_question,
        'answer': answer,
        'closest_item': closest_item,
        'score': score,
        'list_of_answers': list_of_answers
    }
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def logout_view(request):
    lboard= Answer.objects.raw("select auth_user.id, username, sum(score) as total from polls_answer, auth_user where auth_user.id=polls_answer.user_id group by user_id order by total desc;")
    leaderboard=OrderedDict()
    for l in lboard:
        leaderboard[l.username]=l.total

    context = {
        'leaderboard': leaderboard,
    }
    print(leaderboard)
    request.session.flush()
    logout(request)
    return render(request, 'polls/logout.html', context)

def login_view(request):

    if request.POST.get('newAccount') is not None:
        return render(request, 'polls/register.html')

    if request.POST.get('login') is not None:
        print("The user clicked login")

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            print("The user is authenticated")
            login(request,user)
            return redirect('polls:index')
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            messages.error(request,'Username or password not correct')
            return render(request, 'polls/login.html')
    else:
        return render(request, 'polls/login.html')
    

def check_similarity(sentence, model, question):
    stops = set(stopwords.words("english"))
    check_sentence = [w for w in sentence.lower().split() if not w in stops]
    doc = question.answer_set.all()
    scores = dict()
    for line in doc:
        print(line)
        line=str(line)
         #line = line[0:len(line)-1]#I think this is needed for escaping '\n'
        words = [w for w in line.lower().split() if not w in stops]
        try:
            scores[line] = model.n_similarity(words, check_sentence)
        except Exception:
            scores=dict()

    return scores


def register(request):
    if request.POST.get('register') is not None:
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            return redirect('polls:index')
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()

    return render(request,'polls/register.html',
                          {'user_form':user_form})



# def q2(request):
#     answer = request.POST.get('answer')
#     model = settings.WORD2VEC
#     newQuestion = request.POST.get('newQuestion')


#     if newQuestion is not None:
#         try:
#             previous_answers = Answer.objects.all().filter(question=request.session['question_id'],user=request.session['username'])[request.session['index'] + 1]
#             print(previous_answers)
#             latest_question = Question.objects.get(pk=request.session['q2'])
#             latest_question.question_text=latest_question.question_text.replace('following','\"'+previous_answers.answer_text+'\"')
#             request.session['index'] =  request.session['index'] + 1
#         except IndexError as e:
#             context = {
#                 'latest_question': None,
#                 'answer': None,
#                 'closest_item': None,
#                 'score': request.session['score'],
#                 'list_of_answers': None,
#             }
#             return render(request, 'polls/q3.html', context)
        
        

#     print ("request.session['question_id']", request.session['question_id'])
#     if request.session.get("q2") is None:
#         isRel = isRelatedTo.objects.get(question1=request.session['question_id'])
#         q2 = isRel.getRelatedQuestion2()
#         #q3 = isRel.getRelatedQuestion3()
#         request.session['index'] = 0
#         request.session['list_of_answers'] = None
#         request.session["q2"]=q2.id
#         #request.session["q3"]=q3.id
    

#     previous_answers = Answer.objects.all().filter(question=request.session['question_id'],user=2)[request.session['index']]

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/familyfeud.css' %}">
{% if messages %}
        {% for message in messages %}
                <script>      
                        alert( "{{ message }}" ); 
                </script>
        {% endfor %}
{% endif %}    

<div style="float:right">
        <form  method="post" action="{% url 'polls:logout_view' %}">
                {% csrf_token %}
                <input style="padding: 5px;color:white; border: 3px solid white; width: 75px; font-size:18px; font-family: helvetica, sans-serif; text-shadow: 1px 1px 3px rgba(0, 0, 0, 1); background: #7db9e8;
                background: -moz-linear-gradient(top, #7db9e8 0%, #207cca 49%, #2989d8 50%, #1e5799 100%);
                background: -webkit-linear-gradient(top, #7db9e8 0%, #207cca 49%, #2989d8 50%, #1e5799 100%);
                background: linear-gradient(to bottom, #7db9e8 0%, #207cca 49%, #2989d8 50%, #1e5799 100%);
                filter: progid: DXImageTransform.Microsoft.gradient( startColorstr='#7db9e8', endColorstr='#1e5799', GradientType=0);" type="submit" name="logout" value="Logout">
        </form>
</div>



<div class="gameBoard">
        
        <div class="score" id="boardScore">{{ score }}</div>

        <div class="questionHolder">
                {% if latest_question %}
                        <span style="margin-top:15px">{{ latest_question.question_text }}</span>
                {% else %}
                        <p>No questions are available.</p>
                {% endif %}
        </div>
        <div>
                <form  method="post">
                        {% csrf_token %}
                        <div class="container">
                                <input style="height:35px; float:left; width:80%; font-size:20px;" size="40px" type="text" name="answer"/>
                                <input style="color: white; float:left; width:15%; margin-left:5px; padding:5px; border: 3px solid white; width: 75px; font-size:18px; font-family: helvetica, sans-serif; text-shadow: 1px 1px 3px rgba(0, 0, 0, 1);" class="button" type="submit" name="submit" value="Add">
                        </div>
                </form>
        </div>

        <div class="colHolder">
                <div class="col1">

                        {% if list_of_answers.items|length == 0 %}
                                {% for i in "x"|ljust:"7" %}
                                <div class="cardHolder" style="perspective: 800px;" >
                                        <div class="card" style="transform-style: preserve-3d;">
                                                <div class="front" style="-webkit-backface-visibility: hidden;"><span class="DBG">{{ forloop.counter }}</span></div>

                                        </div>
                                </div>
                                {% endfor %}
                        {% endif %}
                        
                        {% for answer,value in list_of_answers.items %}
                                {% if forloop.counter <= 7 %}
                                <div class="cardHolder" style="perspective: 800px;" >
                                        <div class="card" style="transform-style: preserve-3d;">
                                                <div class="back DBG" style="-webkit-backface-visibility: visible; ">
                                                        <span >{{ answer }}</span>
                                                        <b class="LBG">{{ value }}</b>
                                                </div>
                                        </div>
                                </div>
                                {% endif %}
                        {% endfor %}

                        {% if list_of_answers.items|length > 0 %}
                                {% for i in "x"|ljust:"7" %}
                                        {% if forloop.counter > list_of_answers|length %}
                                        <div class="cardHolder" style="perspective: 800px;" >
                                                <div class="card" style="transform-style: preserve-3d;">
                                                        <div class="front" style="-webkit-backface-visibility: hidden; ">
                                                                <span class="DBG">{{ forloop.counter }}</span>
                                                        </div>
                                                </div>
                                        </div>
                                        {% endif %}
                                {% endfor %}
                        {% endif %}



                </div>
                <div class="col2" style="float: right;">

                        {% if list_of_answers.items|length == 0 %}
                                {% for i in "x"|ljust:"7" %}

                                <div class="cardHolder" style="perspective: 800px;">
                                        <div class="card" style="transform-style: preserve-3d;">
                                        <div class="front" style="-webkit-backface-visibility: visible;"><span class="DBG">{{ forloop.counter|add:"7" }}</span></div>
                                        <div class="back DBG" style="-webkit-backface-visibility: hidden; z-index: 0; transform: matrix3d(1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1);"><span>{{ answer }}</span><b class="LBG"></b></div>
                                        </div>
                                </div>
                                {% endfor %}
                        {% endif %}

                        {% for answer,value in list_of_answers.items %}
                        {% if forloop.counter > 7 %}
                        <div class="cardHolder" style="perspective: 800px;">
                                <div class="card" style="transform-style: preserve-3d;">
                                <div class="back DBG" style="-webkit-backface-visibility: visible; z-index: 0;"><span>{{ answer }}</span><b class="LBG">{{ value }}</b></div>
                                </div>
                        </div>
                        {% endif %}
                        {% endfor %}

                        {% if list_of_answers.items|length > 0 %}
                                {% for i in "x"|ljust:"7" %}
                                        {% if forloop.counter|add:"7" > list_of_answers|length %}
                                        <div class="cardHolder" style="perspective: 800px;" >
                                                <div class="card" style="transform-style: preserve-3d;">
                                                <div class="front" style="-webkit-backface-visibility: visible; ">
                                                        <span class="DBG">{{ forloop.counter|add:"7" }}</span> 
                                                </div>
                                                </div>
                                        </div>
                                        {% endif %}
                                {% endfor %}
                        {% endif %}


                </div>
        </div>

        <form  method="post" action="{% url 'polls:index' %}">   <!--polls:q2-->
                        {% csrf_token %}
                        <div class="btnHolder">
                                <input style="text-align:center; color:white; border: 3px solid white;font-size:18px; font-family: helvetica, sans-serif; text-shadow: 1px 1px 3px rgba(0, 0, 0, 1); background: #7db9e8;
                                background: -moz-linear-gradient(top, #7db9e8 0%, #207cca 49%, #2989d8 50%, #1e5799 100%);
                                background: -webkit-linear-gradient(top, #7db9e8 0%, #207cca 49%, #2989d8 50%, #1e5799 100%);
                                background: linear-gradient(to bottom, #7db9e8 0%, #207cca 49%, #2989d8 50%, #1e5799 100%);
                                filter: progid: DXImageTransform.Microsoft.gradient( startColorstr='#7db9e8', endColorstr='#1e5799', GradientType=0);" class="button" type="submit" name="nextQuestion" value="Next Question"/>
                        </div>
                </form>

        

       
                        
</div>

polls/templates/polls/login.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/familyfeud.css' %}">

<div class="gameBoard">
        
        
        <div>
                
                        <div class="questionHolder" style="font-size:19px; height:250px; line-height: 45px; margin-top:5%">

                                {% if messages %}

                                        {% for message in messages %}
                                        <p style="color:indianred; margin-top:2px; margin-bottom:-10px; font-size: 16px ">{{ message }}</p>{% endfor %}
                                {% else %}
                                         <p style="margin-top:2px; margin-bottom:-10px; color: #deeeff; font-size: 16px"> User not logged in</p>
                                {% endif %}

                                <form  method="post" action="{% url 'polls:login_view' %}">
                                        {% csrf_token %}
                                        Username: <input style="height:35px; width:30%; font-size:20px;" size="40px" type="text" name="username"/>
                                        <br>
                                        Password: <input style="height:35px; width:30%; font-size:20px;" size="40px" type="password" name="password"/>
                                        <br>
                                        <input style="color: white; border: 3px solid white; margin-left:90px; float: inherit; font-size:18px; width:30%; font-family: helvetica, sans-serif; text-shadow: 1px 1px 3px rgba(0, 0, 0, 1);" class="button" type="submit" name="login" value="Login">
                                        <div style="border-bottom: 2px;background: black; height: 1px; margin-top:20px; width: 30%; text-align: center; left:35%; position: absolute;">      
                                        <span style="background: #deeeff; margin-top:-10px; color:#666"> New to our game?</span>
                                </form>

                                <form method="post" action="{% url 'polls:register' %}">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <input style="margin-top: 5px; background-color:gray; color: white; border: 3px solid #fff; width:100%; float: inherit; font-size:18px; font-family: helvetica, sans-serif; text-shadow: 1px 1px 3px rgba(0, 0, 0, 1);" type="submit" name="newAccount" value="Create a new account">
                                </form>
                          </div>

                
        </div>

        

        
        

       
                        
</div>

polls/templates/polls/logout.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/familyfeud.css' %}">

<div class="gameBoard">
        <div class="score" id="boardScore">:-)</div>
        <div style="text-align: center; display: inline-block; margin:0 auto; height:auto" class="questionHolder">
                {% if messages %}

                {% for message in messages %}
                        <p style="color:indianred; margin-top:2px; margin-bottom:-10px; font-size: 16px ">{{ message }}</p>{% endfor %}
                {% else %}
                        <span class="question">Thanks for playing with us!</span>
                {% endif %}

                <div class="colHolder" style="background:#deeeff; overflow: scroll; height:400px">
                        <div class="col1">
                                {% for user,total in leaderboard.items %}
                                        <div class="cardHolder" style="perspective: 800px;" >
                                                <div class="card" style="transform-style: preserve-3d;">
                                                        <div class="back DBG" style="-webkit-backface-visibility: visible; ">
                                                                <span style="color:white; width:25px">{{ forloop.counter }}.</span>
                                                                <span style="color:white; ">{{ user }}</span>
                                                                <b class="LBG">{{ total }}</b>
                                                        </div>
                                                </div>
                                        </div>
                                {% endfor %}
                        </div>
                </div>
                <div style="text-align: center; display: inline-block; margin:0 auto">
                        <a href="/polls" >Start a new game</a> 
                </div>
        </div>     
        
</div>

polls/templates/polls/register.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/familyfeud.css' %}">

<div class="gameBoard" style="height:50%">
        
        
        <div>
                
                        <div class="questionHolder" style="font-size:19px; height:50%; line-height: 50px; margin-top:5%">

                                {% if user_form.username.errors %}
                                        <p style="color:indianred; margin-bottom:-40px">{{ user_form.username.errors.as_text }}</p>
                                {% else %}
                                         <p style="margin-bottom:-40px; color: #deeeff;"> User already exists</p>
                                {% endif %}

                                <form  method="post">
                                        {% csrf_token %}
                                        Username: {{user_form.username}}
                                        <br>
                                        Password: {{user_form.password}}
                                        <br>
                                        <input style="color: white; border: 3px solid white; margin-left:90px; float: inherit; font-size:18px; width:30%; font-family: helvetica, sans-serif; text-shadow: 1px 1px 3px rgba(0, 0, 0, 1);" class="button" type="submit" name="register" value="Register">
                                </form>
                          </div>

                
       
                        
</div>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>